### ISSUE TITLE
Cannot find module '../../grow.json

### ISSUE THREAD

**Issue by cloudzombie** [CommonGarden/Grow-IoT#156]
I am running on Digital Ocean, Meteor App is up and running, User is made. 

```
mkdir my-cool-plant
cd my-cool-plant
npm init -y
npm install --save grow.js

```

I get this error

```
Error: Cannot find module '../../grow.json'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at new GROWJS (/root/my-cool-plant/node_modules/grow.js/grow.js:32:21)
    at Object.<anonymous> (/root/my-cool-plant/plant.js:5:12)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
```

So I go and make a grow.json and put...

```
 "host": "http://localhost:3000",
 "thing": {...}
```

Which gives me this error

```
SyntaxError: /root/my-cool-plant/grow.json: Unexpected token :
    at Object.parse (native)
    at Object.Module._extensions..json (module.js:424:27)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at new GROWJS (/root/my-cool-plant/node_modules/grow.js/grow.js:32:21)
    at Object.<anonymous> (/root/my-cool-plant/plant.js:5:12)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
```

What is correct way to connect to localhost with grow.json?

**Comment by JakeHartnell** [comment]
Ah sorry, need to update the docs again. I'm trying to get things to an Alpha release state. It's looks like a JSON parse error, so your JSON isn't formated correctly (it can be picky). Try putting your grow file in a validator like: https://jsonformatter.curiousconcept.com/

Also, checkout the https://github.com/CommonGarden/Grow.js library for updated docs. I've created a new version that doesn't require a Grow.json file, you can try it out with:

```
npm install Grow.js
```

Note the capital `G`.

Hope that's helpful. Also if you are connecting to a digital ocean instance you're going to want to connect to the IP address of that instance. See [connecting devices.](https://github.com/CommonGarden/Grow.js#connecting-devices)

Hope that helps, I'm going to leave this open until I update the docs, I'll ping you when they're better.

**Comment by JakeHartnell** [comment]
I've updated the Readme. Take another look and let me know if you have any problems.
