### ISSUE TITLE
 TypeError: _this._afterConnect is not a function

### ISSUE THREAD

**Issue by cloudzombie** [CommonGarden/Grow-IoT#163]
So following the README now running `node light.js
` gets me this error

```
Grow server connection established.
/root/my-plant-light/node_modules/Grow.js/dist/Grow.umd.js:469
          _this._afterConnect(callback, result);
                ^

TypeError: _this._afterConnect is not a function
    at /root/my-plant-light/node_modules/Grow.js/dist/Grow.umd.js:469:17
    at self._callbacks.(anonymous function) (/root/my-plant-light/node_modules/Grow.js/node_modules/ddp/lib/ddp-client.js:434:16)
    at DDPClient._message (/root/my-plant-light/node_modules/Grow.js/node_modules/ddp/lib/ddp-client.js:156:7)
    at null.<anonymous> (/root/my-plant-light/node_modules/Grow.js/node_modules/ddp/lib/ddp-client.js:96:10)
    at emitOne (events.js:77:13)
    at emit (events.js:169:7)
    at EventTarget.dispatchEvent (/root/my-plant-light/node_modules/Grow.js/node_modules/ddp/node_modules/faye-websocket/lib/faye/websocket/api/event_target.js:24:10)
    at instance._receiveMessage (/root/my-plant-light/node_modules/Grow.js/node_modules/ddp/node_modules/faye-websocket/lib/faye/websocket/api.js:142:10)
    at null.<anonymous> (/root/my-plant-light/node_modules/Grow.js/node_modules/ddp/node_modules/faye-websocket/lib/faye/websocket/api.js:34:49)
    at emitOne (events.js:82:20)
```

I am running the process as root on the same server as the Grow-IoT instance.

**Comment by JakeHartnell** [comment]
> I am running the process as root on the same server as the Grow-IoT instance.

Ah, haven't tried that yet. Do you have a specific microcontroller you are using?

I think this probably a [Grow.js](http://github.com/CommonGarden/Grow.js) issue, will take a closer look tomorrow!

**Comment by cloudzombie** [comment]
I am not using a microcontroller currently, I ordered an Arduino Uno which my partner has for testing purposes, We are going to be controlling the atlas-scientific line of sensors specifically though with Arduino Uno, Raspberry Pi 3 and a Linux mainbox to run Grow-IoT in development. The end goal is to push it galaxy hosting on a subdomain of ours for dead simple access and monitoring for the less tech inclined workers I have. 

And you are correct, The specific error is caused by [Grow.js](https://github.com/CommonGarden/Grow.js)

Line 87 

`this._afterConnect(callback, result);
`

When running `light.js` from Grow-Iot Quickstart, this line causes this error

```
Grow server connection established.
/home/cloud/my-plant-light/node_modules/Grow.js/dist/Grow.umd.js:469
          _this._afterConnect(callback, result);
                ^

TypeError: _this._afterConnect is not a function
    at /home/cloud/my-plant-light/node_modules/Grow.js/dist/Grow.umd.js:469:17
    at self._callbacks.(anonymous function) (/home/cloud/my-plant-light/node_modules/Grow.js/node_modules/ddp/lib/ddp-client.js:434:16)
    at DDPClient._message (/home/cloud/my-plant-light/node_modules/Grow.js/node_modules/ddp/lib/ddp-client.js:156:7)
    at null.<anonymous> (/home/cloud/my-plant-light/node_modules/Grow.js/node_modules/ddp/lib/ddp-client.js:96:10)
    at emitOne (events.js:77:13)
    at emit (events.js:169:7)
    at EventTarget.dispatchEvent (/home/cloud/my-plant-light/node_modules/Grow.js/node_modules/ddp/node_modules/faye-websocket/lib/faye/websocket/api/event_target.js:24:10)
    at instance._receiveMessage (/home/cloud/my-plant-light/node_modules/Grow.js/node_modules/ddp/node_modules/faye-websocket/lib/faye/websocket/api.js:142:10)
    at null.<anonymous> (/home/cloud/my-plant-light/node_modules/Grow.js/node_modules/ddp/node_modules/faye-websocket/lib/faye/websocket/api.js:34:49)
    at emitOne (events.js:82:20)
```

**Comment by JakeHartnell** [comment]
Ok, I'm having trouble reproducing this. A few questions:
1. What version of Node are you using? Try `node -v`.
2. When you run `npm install` are there any errors?
3. Is there anything in particular you do to produce the error?
4. Are using Mac or Linux?

We'll figure it out. I'll keep playing around, but more info would be helpful.

**Comment by JakeHartnell** [comment]
Closing this for now, feel free to reopen if the problem persists. There's still an issue open in Grow.js: https://github.com/CommonGarden/Grow.js/issues/62
