### ISSUE TITLE
Exception on first run

### ISSUE THREAD

**Issue by jernst** [CommonGarden/Grow-IoT#383]
Followed the instructions:
* Installed Meteor
* cloned the repo
* `meteor npm install`
* `meteor`

This last command produces:
```
[[[[[ ~/git/github.com/CommonGarden/Grow-IoT ]]]]]

=> Started proxy.                             
=> Started MongoDB.                           
/home/buildmaster/.meteor/packages/mwc_synthesis-assets/.0.1.5.14yg9cj++os+web.browser+web.cordova/plugin.synthesis-assets.os/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:190
      throw error;
      ^

TypeError: Cannot set property './template.LICENSE-W3C.js' of undefined
    at ImportScanner._checkSourceAndTargetPaths (/tools/isobuild/import-scanner.js:279:7)
    at /tools/isobuild/import-scanner.js:186:12
    at Array.forEach (native)
    at ImportScanner.addInputFiles (/tools/isobuild/import-scanner.js:185:11)
    at /tools/isobuild/compiler-plugin.js:1037:15
    at Array.forEach (native)
    at Function.computeJsOutputFilesMap (/tools/isobuild/compiler-plugin.js:1008:19)
    at ClientTarget._emitResources (/tools/isobuild/bundler.js:1059:8)
    at /tools/isobuild/bundler.js:830:12
```
(stack trace continues).

Why is that, and how can I proceed?

This is Arch Linux, latest and greatest, on VirtualBox, with the meteor 1.5-1 package from AUR, nodejs 8.2.1-1.

**Comment by aruntk** [comment]
@jernst Looks like a file path issue. Checking.

**Comment by aruntk** [comment]
@jernst Please checkout branch [issue-383-fix](https://github.com/CommonGarden/Grow-IoT/tree/issue-383-fix) and let me know if the issue persists.

**Comment by jernst** [comment]
Works! Thank you.

**Comment by aruntk** [comment]
@jernst Glad to help. Thanks for reporting the issue. :)
