### ISSUE TITLE
Server cloud deployment UI errors

### ISSUE THREAD

**Issue by catbarph** [CommonGarden/Grow-IoT#403]
Control buttons in cloud-hosted webUI seem to be the only thing not working. 
Here's a dump from my chrome console:
```
things:1 Error in event handler for (unknown): TypeError: Cannot read property 'name' of null
    at Object.onSettings (chrome-extension://gghkfhpblkcmlkmpcpgaajbbiikbhpdi/model.js:314:14)
    at Object.onInitEnabled (chrome-extension://gghkfhpblkcmlkmpcpgaajbbiikbhpdi/model.js:367:12)
    at EventHandler.g.EventHandler.EventHandler.onInitEnabled (chrome-extension://gghkfhpblkcmlkmpcpgaajbbiikbhpdi/eventhandler.js:157:25)
    at chrome-extension://gghkfhpblkcmlkmpcpgaajbbiikbhpdi/vichrome.js:18:24
meteor.js?hash=6d285d84547b3dad9717a7c89c664b61b45ea3d8:942 Exception from Tracker recompute function:
meteor.js?hash=6d285d84547b3dad9717a7c89c664b61b45ea3d8:942 ReferenceError: Raphael is not defined
    at new JustGage (modules.js?hash=0959a7fc2b69ee3d46cdfd5f1e0e8b385f210aef:325990)
    at JustGauge.componentDidMount (JustGage.jsx:14)
    at CallbackQueue.notifyAll (modules.js?hash=0959a7fc2b69ee3d46cdfd5f1e0e8b385f210aef:9173)
    at ReactReconcileTransaction.close (modules.js?hash=0959a7fc2b69ee3d46cdfd5f1e0e8b385f210aef:19432)
    at ReactReconcileTransaction.closeAll (modules.js?hash=0959a7fc2b69ee3d46cdfd5f1e0e8b385f210aef:10314)
    at ReactReconcileTransaction.perform (modules.js?hash=0959a7fc2b69ee3d46cdfd5f1e0e8b385f210aef:10261)
    at ReactUpdatesFlushTransaction.perform (modules.js?hash=0959a7fc2b69ee3d46cdfd5f1e0e8b385f210aef:10248)
    at ReactUpdatesFlushTransaction.perform (modules.js?hash=0959a7fc2b69ee3d46cdfd5f1e0e8b385f210aef:8928)
    at Object.flushBatchedUpdates (modules.js?hash=0959a7fc2b69ee3d46cdfd5f1e0e8b385f210aef:9011)
    at ReactDefaultBatchingStrategyTransaction.closeAll (modules.js?hash=0959a7fc2b69ee3d46cdfd5f1e0e8b385f210aef:10314)
model.js:212 Uncaught TypeError: Cannot read property 'getName' of null
    at Object.isInCommandMode (model.js:212)
    at Object.onFocus (model.js:339)
    at EventHandler.g.EventHandler.EventHandler.onFocus (eventhandler.js:66)
    at HTMLDocument.<anonymous> (eventhandler.js:84)
model.js:243 Uncaught TypeError: Cannot read property 'blur' of null
    at Object.onBlur (model.js:243)
    at EventHandler.g.EventHandler.EventHandler.onBlur (eventhandler.js:18)
    at HTMLDocument.<anonymous> (eventhandler.js:87)
model.js:212 Uncaught TypeError: Cannot read property 'getName' of null
    at Object.isInCommandMode (model.js:212)
    at Object.onFocus (model.js:339)
    at EventHandler.g.EventHandler.EventHandler.onFocus (eventhandler.js:66)
    at HTMLDocument.<anonymous> (eventhandler.js:84)
model.js:243 Uncaught TypeError: Cannot read property 'blur' of null
    at Object.onBlur (model.js:243)
    at EventHandler.g.EventHandler.EventHandler.onBlur (eventhandler.js:18)
    at HTMLDocument.<anonymous> (eventhandler.js:87)
model.js:212 Uncaught TypeError: Cannot read property 'getName' of null
    at Object.isInCommandMode (model.js:212)
    at Object.onFocus (model.js:339)
    at EventHandler.g.EventHandler.EventHandler.onFocus (eventhandler.js:66)
    at HTMLDocument.<anonymous> (eventhandler.js:84)
model.js:243 Uncaught TypeError: Cannot read property 'blur' of null
    at Object.onBlur (model.js:243)
    at EventHandler.g.EventHandler.EventHandler.onBlur (eventhandler.js:18)
    at HTMLDocument.<anonymous> (eventhandler.js:87)
model.js:212 Uncaught TypeError: Cannot read property 'getName' of null
    at Object.isInCommandMode (model.js:212)
    at Object.onFocus (model.js:339)
    at EventHandler.g.EventHandler.EventHandler.onFocus (eventhandler.js:66)
    at HTMLDocument.<anonymous> (eventhandler.js:84)
model.js:243 Uncaught TypeError: Cannot read property 'blur' of null
    at Object.onBlur (model.js:243)
    at EventHandler.g.EventHandler.EventHandler.onBlur (eventhandler.js:18)
    at HTMLDocument.<anonymous> (eventhandler.js:87)
model.js:212 Uncaught TypeError: Cannot read property 'getName' of null
    at Object.isInCommandMode (model.js:212)
    at Object.onFocus (model.js:339)
    at EventHandler.g.EventHandler.EventHandler.onFocus (eventhandler.js:66)
    at HTMLDocument.<anonymous> (eventhandler.js:84)
model.js:243 Uncaught TypeError: Cannot read property 'blur' of null
    at Object.onBlur (model.js:243)
    at EventHandler.g.EventHandler.EventHandler.onBlur (eventhandler.js:18)
    at HTMLDocument.<anonymous> (eventhandler.js:87)
model.js:212 Uncaught TypeError: Cannot read property 'getName' of null
    at Object.isInCommandMode (model.js:212)
    at Object.onFocus (model.js:339)
    at EventHandler.g.EventHandler.EventHandler.onFocus (eventhandler.js:66)
    at HTMLDocument.<anonymous> (eventhandler.js:84)
model.js:243 Uncaught TypeError: Cannot read property 'blur' of null
    at Object.onBlur (model.js:243)
    at EventHandler.g.EventHandler.EventHandler.onBlur (eventhandler.js:18)
    at HTMLDocument.<anonymous> (eventhandler.js:87)
model.js:212 Uncaught TypeError: Cannot read property 'getName' of null
    at Object.isInCommandMode (model.js:212)
    at Object.onFocus (model.js:339)
    at EventHandler.g.EventHandler.EventHandler.onFocus (eventhandler.js:66)
    at HTMLDocument.<anonymous> (eventhandler.js:84)
model.js:243 Uncaught TypeError: Cannot read property 'blur' of null
    at Object.onBlur (model.js:243)
    at EventHandler.g.EventHandler.EventHandler.onBlur (eventhandler.js:18)
    at HTMLDocument.<anonymous> (eventhandler.js:87)
```

**Comment by JakeHartnell** [comment]
Removed justgage and fixed this, thanks for the bug report.
