### ISSUE TITLE
Error running test device

### ISSUE THREAD

**Issue by JakeHartnell** [CommonGarden/Grow-IoT#421]
`node tests/test-grow-hub.js` fails with the following:

```
module.js:487
    throw err;
    ^

Error: Cannot find module 'Grow.js'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/jacobhartnell/Dev/GROW/Grow-IoT/tests/test-grow-hub.js:1:77)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)

```

This is likely a result of [yarn workspaces](https://yarnpkg.com/blog/2017/08/02/introducing-workspaces/
) not being set up correctly... packages in the `packages` directory should be available elsewhere.

**Comment by JakeHartnell** [comment]
Fixed with `lerna bootstrap`.
